#! /usr/bin/env bash
return
if [[ -z $(pidof -s socat) ]]; then
	if [[ -S /tmp/.X11-unix/X0 ]]; then
		rm /tmp/.X11-unix/X0
	fi
	sudo socat -b65536 UNIX-LISTEN:/tmp/.X11-unix/X0,fork,mode=777 vsock-connect:2:106000 >/dev/null 2>&1 &
fi
export DISPLAY=:0
export LIBGL_ALWAYS_INDIRECT=1
export PULSE_SERVER=tcp:$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}') #GWSL

export XDG_SESSION_TYPE="x11"
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_SESSION_CLASS="user"
export XDG_SESSION_DESKTOP=ubuntu
# export XDG_CURRENT_DESKTOP=ubuntu:GNOME
export XDG_CURRENT_DESKTOP=ubuntu:mate
export DESKTOP_SESSION=ubuntu
export GDMSESSION=ubuntu
